name: Tests

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.10", "3.11", "3.12"]

        steps:
        - uses: actions/checkout@v4 # v4.2.2

        - name: Set up Python
          uses: actions/setup-python@v5 # v5.3.0
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[dev]

        - name: Run tests with pytest
          run: pytest tests/ --cov=qickit --cov-report=xml

        - name: Run mypy
          run: mypy qickit

        - name: Run ruff
          run: ruff check qickit

        - name: Report to codecov
          uses: codecov/codecov-action@v5 # v5.1.2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}

        - name: Report to Codacy
          uses: codacy/codacy-coverage-reporter-action@v1.3.0  # v1.3.0
          with:
            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
            coverage-reports: coverage.xml
